# Generated by Django 4.2.5 on 2023-09-16 19:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='VideoTranscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('video_url', models.URLField(unique=True)),
                ('video_file', models.FileField(upload_to='videos/')),
                ('audio_file', models.FileField(upload_to='audio/')),
                ('transcription_text', models.TextField(blank=True, null=True)),
                ('downloaded_at', models.DateTimeField(auto_now_add=True)),
                ('transcribed_at', models.DateTimeField(blank=True, null=True)),
            ],
        ),
    ]
