# Generated by Django 4.2.5 on 2023-11-07 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_video'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='audio_file',
            field=models.FileField(blank=True, null=True, upload_to='audio/'),
        ),
        migrations.AddField(
            model_name='video',
            name='transcription_textundefined',
            field=models.TextField(blank=True, null=True),
        ),
    ]
